AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public virtual DbSet<Shelter> Shelters { get; set; }
    public DbSet<Animal> Animals { get; set; }
    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Models/Animals.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace AnimalShelter.Models
{
  public class Animal
  {
    public string Breed { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public int Age { get; set; }
    public int AnimalId { get; set; }
    public int ShelterId { get; set; }
    public virtual Shelter Shelter { get; set; }
  }
  
}

AnimalShelter/Models/Shelter.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
  public class Shelter
  {
    public Shelter()
    {
      this.Animals = new HashSet<Animal>();
    }
    public int ShelterId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Animal> Animals { get; set; }

  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;
    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.Include(animals =>animals.Shelter).ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
    Animal thisAnimal = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
    return View(thisAnimal);
    }
    public ActionResult Edit(int id)
    {
      var thisAnimal = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
      return View(thisAnimal);
    }
    [HttpPost]
    public ActionResult Edit(Animal animal)
    {
      _db.Entry(animal).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisAnimal = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
      return View(thisAnimal);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisAnimal = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
      _db.Animals.Remove(thisAnimal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add a new animal</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Breed)
  @Html.TextBoxFor(model => model.Breed)
  <br>
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Gender)
  @Html.TextBoxFor(model => model.Gender)
  <br>
  @Html.LabelFor(model => model.Age)
  @Html.TextBoxFor(model => model.Age)
  <br>
  <input type="submit" value="Add new animal"/>
}
<p>@Html.ActionLink("Show all items", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

AnimalShelter/Views/Animals/Delete.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Are you sure you want to delete this entry?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}
@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)<h3>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)<h3>
<h3>@Html.DisplayNameFor(model => model.Age): @Html.DisplayFor(model => model.Age)<h3>
<p>@Html.ActionLink("Edit Animal", "Edit", new {id = Model.AnimalId})</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Delete Animal","Delete", new { id = Model.AnimalId})</p>

AnimalShelter/Views/Animals/Edit.cshtml
@{
  Layout = "_Layout";
}
@model AnimalShelter.Models.Animal

<h2>Edit</h2>

<h4>Edit @Html.DisplayFor(model => model.Name):</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.AnimalId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Age)
  @Html.EditorFor(model => model.Age)
  <br>
  @Html.LabelFor(model => model.Breed)
  @Html.EditorFor(model => model.Breed)
  <br>
  @Html.LabelFor(model => model.Gender)
  @Html.EditorFor(model => model.Gender)
  <br>
  <input type="submit" value = "Save"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}
 
@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Animal>;

<h1>Animals</h1>
@if (Model.Count == 0)
{
  <p>Nothing here bro.</p>
}
<ul>
  @foreach (Animal animal in Model)
  {
  <li>@Html.ActionLink($"{item.Description}","Details", new { id = animal.AnimalId})</li>
  }
</ul>
<p>@Html.ActionLink("Add new animal","Create")</p>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
    <h1>Welcome to the Animal Shelter!</h1>
    <p>@Html.ActionLink("See all the animals","Index","Animals")</p>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Animal Shleter</title>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="box">
      @RenderBody()
    </div>
  </body>
</html>

AnimalShelter/Views/Shelters/Index.cshtml
@* @{
  Layout = "_Layout";
}
 
@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Animal>;

<h1>Shelters</h1>
@if (Model.Count == 0)
{
  <p>Nothing here bro.</p>
}
@foreach (Animal animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}","Details", new { id = animal.AnimalId}) | @animal.Shelter.Name </li>
  <br>
}


<p>@Html.ActionLink("Add new animal","Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p> *@